### PR TITLE
Validate options when generating pact publish URL

### PR DESCRIPTION
**Pull request by mefellows**
Fixes issue #12:

* Returns a rejected promise with a proper error message
* Validates a that a broker url is provided and a valid consumer/provider object exists in the Pact file

### CODE REVIEW

**Comment by mefellows** [comment]
Travis CI issues seem to have disappeared and build is green again (and running nice and quick). I've currently left Mac OSX builds out - do we want them back? Not sure how much value they're adding.

**Comment by mboudreau** [comment]
Please do.  I want to make sure all our code works in all OS'.  We've been
burned by this before and I don't want it happening again.

**Comment by mefellows** [comment]
Np, I have added them back in. Any objections to merging this now (Mac builds still seem to be affected in TravisCI)? Normally I would wait, but this PR fixes a problem we have released so I don't see harm in releasing on the small chance it doesn't build on OSX (and even then I'll be skeptical as I build on OSX locally).

**Comment by mefellows** [comment]
OK, we're proper green now. Err, well sorta (looking at you Appveyor!).

**Pull request merged**
