### PR TITLE
Return output to promise in verification process

### PR DESCRIPTION
**Pull request by mefellows**
Fixes issue #7.

Essentially, we log all output as before, but we also store it in a string variable that is passed back to the promise chain. This allows clients (such as pact-foundation/pact-js) to provide better messaging to their users.

### CODE REVIEW

**Comment by mboudreau** [comment]
@mefellows Check why the build is failing and please use the same promise library throughout the project.  We can't have a mismash of libraries trying to do the same thing.

**Comment by mefellows** [comment]
Not sure what you mean with promise libs, I didn't change that (AFAIK). Weirdly the build is failing intermittently - never a good thing.

**Comment by mboudreau** [comment]
You added Promise.reject within an integration test, which doesn't resolve to anything:

```
return expect(verifier.verify().catch(function(err) {
							if (!_.isEmpty(err) && err.indexOf("unexpected token at 'Unauthorized'") > -1) {
								return Promise.reject(new Error("failed"));
							}
						})).to.eventually.be.rejectedWith(Error, "failed");
```

You should be using q.reject instead. I'm guessing the build is failing intermittently because of an async test that calls done too quickly.

**Comment by mefellows** [comment]
Right. I didn't add a new Promise in this PR though (look at the diff) so
that's a bit weird. I'll look into it, thanks for digging through it.

On Thu, Jun 9, 2016 at 11:05 AM, Michel Boudreau <notifications@github.com>
wrote:

> You added Promise.reject within an integration test, which doesn't resolve
> to anything:
>
> return expect(verifier.verify().catch(function(err) {
>                             if (!_.isEmpty(err) && err.indexOf("unexpected token at 'Unauthorized'") > -1) {
>                                 return Promise.reject(new Error("failed"));
>                             }
>                         })).to.eventually.be.rejectedWith(Error, "failed");
>
> You should be using q.reject instead. I'm guessing the build is failing
> intermittently because of an async test that calls done too quickly.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/pact-foundation/pact-node/pull/8#issuecomment-224775840>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AADSjC1Q91s8l5580T8RyuyZJrSXUeUZks5qJ2bKgaJpZM4IxbIH>
> .
>



-- 
Matt Fellows
- http://www.onegeek.com.au/

**Pull request closed without merging**
